### ISSUE TITLE
Sentry Middleware

### ISSUE THREAD

**Issue by bralbral** [benyaming/aiogram-bot-template#1]
Hi! Could you explain how  SentryMiddleware works ? There are no alerts when i triggered `raise Exception()`. I receive alerts when using 'logger.error' or 'logger.warn'

Thanks

**Comment by benyaming** [comment]
Hey, could you share your project?

Actually I still didn't used this template, but you also can [look here](https://github.com/benyaming/israel_bus_info_bot/blob/master/bus_bot/middleware/sentry_middleware.py) - the Middleware works as expected

**Comment by bralbral** [comment]
Thanks. It is suitable.
